const yogaAcademiesData = [
  {
    id: 1,
    name: "Zen Yoga Center",
    location: "City A",
    instructors: ["John Doe", "Jane Smith"],
    rating: 4.5,
    imageURL: "https://via.placeholder.com/150",
    description: "A peaceful place for yoga and meditation.",
  },
  {
    id: 2,
    name: "Serene Asanas Studio",
    location: "City B",
    instructors: ["Alice Johnson", "Bob Williams"],
    rating: 4.2,
    imageURL: "https://via.placeholder.com/150",
    description: "Explore the tranquility through various yoga practices.",
  },
  {
    id: 3,
    name: "Sunshine Yoga Hub",
    location: "City C",
    instructors: ["Sam Brown", "Eva Davis"],
    rating: 4.8,
    imageURL: "https://via.placeholder.com/150",
    description: "Connect with your inner self under the sunlit ambiance.",
  },
  {
    id: 4,
    name: "Eternal Bliss Yoga Institute",
    location: "City D",
    instructors: ["Grace Turner", "Mark Anderson"],
    rating: 4.6,
    imageURL: "https://via.placeholder.com/150",
    description: "Experience eternal bliss through our yoga practices.",
  },
  {
    id: 5,
    name: "Harmony Yoga Sanctuary",
    location: "City E",
    instructors: ["Olivia White", "Charlie Lee"],
    rating: 4.4,
    imageURL: "https://via.placeholder.com/150",
    description: "Find harmony and balance with our expert instructors.",
  },
  {
    id: 6,
    name: "Tranquil Yoga Retreat",
    location: "City F",
    instructors: ["Michael Turner", "Sophie Davis"],
    rating: 4.9,
    imageURL: "https://via.placeholder.com/150",
    description: "Embark on a journey of tranquility at our yoga retreat.",
  },
  {
    id: 7,
    name: "Lotus Wellness Center",
    location: "City G",
    instructors: ["Ava Roberts", "Jack Thompson"],
    rating: 4.3,
    imageURL: "https://via.placeholder.com/150",
    description: "Discover the lotus path to holistic wellness.",
  },
  {
    id: 8,
    name: "Mystic Yoga Haven",
    location: "City H",
    instructors: ["Daniel Miller", "Sophia Brown"],
    rating: 4.7,
    imageURL: "https://via.placeholder.com/150",
    description: "Unleash mystic energy through profound yoga sessions.",
  },
  {
    id: 9,
    name: "Spiritual Harmony Yoga",
    location: "City I",
    instructors: ["Emma Turner", "Noah Harris"],
    rating: 4.1,
    imageURL: "https://via.placeholder.com/150",
    description: "Experience spiritual harmony with our yoga teachings.",
  },
];

const yogaCoursesData = [
  {
    id: 1,
    name: "Beginner Yoga Flow",
    instructor: "John Doe",
    duration: "1 hour",
    level: "Beginner",
    academy: "Zen Yoga Center",
    rating: 4.5,
    imageURL: "https://via.placeholder.com/150",
    description:
      "A gentle introduction to basic yoga poses and flows for beginners.",
  },
  {
    id: 2,
    name: "Vinyasa Power Hour",
    instructor: "Alice Johnson",
    duration: "1.5 hours",
    level: "Intermediate",
    academy: "Serene Asanas Studio",
    rating: 4.2,
    imageURL: "https://via.placeholder.com/150",
    description:
      "Energizing and dynamic Vinyasa flow suitable for intermediate practitioners.",
  },
  {
    id: 3,
    name: "Meditation and Mindfulness",
    instructor: "Sam Brown",
    duration: "45 minutes",
    level: "All Levels",
    academy: "Sunshine Yoga Hub",
    rating: 4.8,
    imageURL: "https://via.placeholder.com/150",
    description:
      "Explore the practice of mindfulness and meditation for inner peace.",
  },
  {
    id: 4,
    name: "Advanced Ashtanga Yoga",
    instructor: "Grace Turner",
    duration: "2 hours",
    level: "Advanced",
    academy: "Eternal Bliss Yoga Institute",
    rating: 4.6,
    imageURL: "https://via.placeholder.com/150",
    description:
      "Challenge yourself with the advanced poses and sequences of Ashtanga Yoga.",
  },
  {
    id: 5,
    name: "Yin Yoga for Relaxation",
    instructor: "Olivia White",
    duration: "1 hour",
    level: "All Levels",
    academy: "Harmony Yoga Sanctuary",
    rating: 4.4,
    imageURL: "https://via.placeholder.com/150",
    description:
      "Gentle and restorative Yin Yoga poses for relaxation and flexibility.",
  },
  {
    id: 6,
    name: "Yoga Nidra Session",
    instructor: "Michael Turner",
    duration: "1 hour",
    level: "All Levels",
    academy: "Tranquil Yoga Retreat",
    rating: 4.9,
    imageURL: "https://via.placeholder.com/150",
    description:
      "Experience deep relaxation and conscious sleep with Yoga Nidra.",
  },
  {
    id: 7,
    name: "Chakra Balancing Workshop",
    instructor: "Ava Roberts",
    duration: "1.5 hours",
    level: "Intermediate",
    academy: "Lotus Wellness Center",
    rating: 4.3,
    imageURL: "https://via.placeholder.com/150",
    description:
      "Learn techniques to balance and align your chakras for overall well-being.",
  },
  {
    id: 8,
    name: "Mystic Energy Yoga",
    instructor: "Daniel Miller",
    duration: "1.5 hours",
    level: "Intermediate",
    academy: "Mystic Yoga Haven",
    rating: 4.7,
    imageURL: "https://via.placeholder.com/150",
    description: "Tap into mystic energies through a powerful yoga session.",
  },
  {
    id: 9,
    name: "Yoga for Spiritual Awakening",
    instructor: "Emma Turner",
    duration: "2 hours",
    level: "Advanced",
    academy: "Spiritual Harmony Yoga",
    rating: 4.1,
    imageURL: "https://via.placeholder.com/150",
    description:
      "Advanced yoga practices for those seeking spiritual awakening.",
  },
];

const myYogaCoursesData = [
  {
    id: 10,
    name: "Morning Sunrise Yoga",
    instructor: "Sophie Davis",
    duration: "1 hour",
    level: "All Levels",
    academy: "Sunshine Yoga Hub",
    rating: 4.7,
    imageURL: "https://via.placeholder.com/150",
    description:
      "Start your day with a refreshing yoga session to energize your body and mind.",
  },
  {
    id: 11,
    name: "Gentle Yoga for Stress Relief",
    instructor: "Jack Thompson",
    duration: "45 minutes",
    level: "Beginner",
    academy: "Lotus Wellness Center",
    rating: 4.5,
    imageURL: "https://via.placeholder.com/150",
    description:
      "Relax and unwind with gentle yoga poses designed to alleviate stress and tension.",
  },
  {
    id: 12,
    name: "Powerful Asanas Workshop",
    instructor: "Noah Harris",
    duration: "2 hours",
    level: "Intermediate",
    academy: "Eternal Bliss Yoga Institute",
    rating: 4.9,
    imageURL: "https://via.placeholder.com/150",
    description:
      "Deep dive into powerful asanas with expert guidance for intermediate practitioners.",
  },
];

export { yogaAcademiesData, yogaCoursesData, myYogaCoursesData };
